// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEIjREXXrH0su-04mfvY9iOA3-YQ1MGP4',
    appId: '1:675110412127:web:1dd6192135fc0e9dd560ea',
    messagingSenderId: '675110412127',
    projectId: 'smart-paint-shop',
    authDomain: 'smart-paint-shop.firebaseapp.com',
    databaseURL: 'https://smart-paint-shop-default-rtdb.firebaseio.com',
    storageBucket: 'smart-paint-shop.firebasestorage.app',
    measurementId: 'G-5PNLMRSS62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWdQclZWNfcCRLdJFlu_xHyGRlg4T8Yo',
    appId: '1:675110412127:android:29a374a81f1c939ed560ea',
    messagingSenderId: '675110412127',
    projectId: 'smart-paint-shop',
    databaseURL: 'https://smart-paint-shop-default-rtdb.firebaseio.com',
    storageBucket: 'smart-paint-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8u99y8xHdxUwBYv-Ry6RmLROsVK_UXM',
    appId: '1:675110412127:ios:993d85bce480aa2dd560ea',
    messagingSenderId: '675110412127',
    projectId: 'smart-paint-shop',
    databaseURL: 'https://smart-paint-shop-default-rtdb.firebaseio.com',
    storageBucket: 'smart-paint-shop.firebasestorage.app',
    iosClientId: '675110412127-q9ftnkfk5g16tbu9u9fg7n1rdj00esve.apps.googleusercontent.com',
    iosBundleId: 'com.example.cHp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8u99y8xHdxUwBYv-Ry6RmLROsVK_UXM',
    appId: '1:675110412127:ios:993d85bce480aa2dd560ea',
    messagingSenderId: '675110412127',
    projectId: 'smart-paint-shop',
    databaseURL: 'https://smart-paint-shop-default-rtdb.firebaseio.com',
    storageBucket: 'smart-paint-shop.firebasestorage.app',
    iosClientId: '675110412127-q9ftnkfk5g16tbu9u9fg7n1rdj00esve.apps.googleusercontent.com',
    iosBundleId: 'com.example.cHp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEIjREXXrH0su-04mfvY9iOA3-YQ1MGP4',
    appId: '1:675110412127:web:d542f153e81c0a20d560ea',
    messagingSenderId: '675110412127',
    projectId: 'smart-paint-shop',
    authDomain: 'smart-paint-shop.firebaseapp.com',
    databaseURL: 'https://smart-paint-shop-default-rtdb.firebaseio.com',
    storageBucket: 'smart-paint-shop.firebasestorage.app',
    measurementId: 'G-MWH97M0NBJ',
  );

}